### ISSUE TITLE
Profile Redirect

### ISSUE THREAD

**Issue by LamiaSK** [malshafai/olesc#6]
Everytime a student wants to search:
The first time it redirects them into the users profile page.
The second or third time it does the search properly.

**Comment by malshafai** [comment]
We will try the following jquery; might enhance it a little to make submit available on search textboxes only

$(document).keypress(
  function(event){
    if (event.which == '13') {
      event.preventDefault();
    }
});

**Comment by malshafai** [comment]
Fixed by modifying the form on the mainmaster page. with setting a default button for the form; and defining a button that does nothing.

 <form id="form1" runat="server" defaultbutton="btnFake">
            <asp:LinkButton ID="btnFake" runat="server" style="display:none" OnClientClick="return false;" ></asp:LinkButton>
